wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1656921842
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 16
      4: 3.8.13
      5: 0.12.19
      8:
      - 5
    visualize:
      conf_mat_test:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_mat_test_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
      conf_mat_train:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_mat_train_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 3
epochs:
  desc: null
  value: 15
lr:
  desc: null
  value: 0.001
max_epochs:
  desc: null
  value: 100
num_classes:
  desc: null
  value: 8
num_workers:
  desc: null
  value: 1
ruta_AIDL_dataloader:
  desc: null
  value: /content/drive/MyDrive/Postgrau_AIDL
shuffle:
  desc: null
  value: false
useTrans:
  desc: null
  value: true
