wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1656921808
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      4: 3.8.13
      5: 0.12.19
      8:
      - 5
batch_size:
  desc: null
  value: 3
epochs:
  desc: null
  value: 15
lr:
  desc: null
  value: 0.001
max_epochs:
  desc: null
  value: 100
num_classes:
  desc: null
  value: 8
num_workers:
  desc: null
  value: 1
ruta_AIDL_dataloader:
  desc: null
  value: /content/drive/MyDrive/Postgrau_AIDL
shuffle:
  desc: null
  value: false
useTrans:
  desc: null
  value: true
